# GLATE's parameter setup
Cora:
  seed: 39788
  learning_rate: 0.0005
  num_hidden: 256
  num_proj_hidden: 256
  activation: 'rrelu'
  base_model: 'GCNConv'
  num_layers: 2
  drop_edge_rate_1: 0.2
  drop_edge_rate_2: 0.4
  drop_feature_rate_1: 0.3
  drop_feature_rate_2: 0.4
  num_epochs: 200
  weight_decay: 0.00001
  tau1: 0.8
  tau2: 0.2